version: '3.7'
services:
  postgresql:
    image: postgres:11
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 15432:80
    networks:
      - postgres_net
    restart: unless-stopped
  amqp:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: "exit 0"

volumes:
  postgres-data:
    driver: local
  rabbit-data:
    driver: local

networks:
  postgres_net:
    driver: bridge
